import Mathlib

namespace CMPLean

variable {𝕜 LA LB XA XS XB : Type*}
variable [Field 𝕜]
variable [AddCommGroup LA] [Module 𝕜 LA]
variable [AddCommGroup LB] [Module 𝕜 LB]
variable [AddCommGroup XA] [Module 𝕜 XA]
variable [AddCommGroup XS] [Module 𝕜 XS]
variable [AddCommGroup XB] [Module 𝕜 XB]

/-- The intrinsic separator message: exactly the separator vectors generated by
A-side row combinations whose internal A-coordinates vanish. -/
def IntrinsicMessage
    (JA : LA →ₗ[𝕜] XA) (JAS : LA →ₗ[𝕜] XS) : Set XS :=
  {s | ∃ l : LA, JA l = 0 ∧ JAS l = s}

/-- Exact basis-free separator factorization for a block-angular linearized
constraint system. No rank, invertibility, smoothness, or genericity hypothesis
is used. -/
theorem separator_factorization
    (JA : LA →ₗ[𝕜] XA)
    (JAS : LA →ₗ[𝕜] XS)
    (JBS : LB →ₗ[𝕜] XS)
    (JB : LB →ₗ[𝕜] XB)
    (s : XS) (b : XB) :
    (∃ l : LA, ∃ m : LB,
      JA l = 0 ∧
      s = JAS l + JBS m ∧
      b = JB m) ↔
    (∃ msg : XS, msg ∈ IntrinsicMessage JA JAS ∧
      ∃ m : LB,
        s = msg + JBS m ∧
        b = JB m) := by
  constructor
  · rintro ⟨l, m, hl, hs, hb⟩
    refine ⟨JAS l, ?_, m, hs, hb⟩
    exact ⟨l, hl, rfl⟩
  · rintro ⟨msg, ⟨l, hl, hmsg⟩, m, hs, hb⟩
    refine ⟨l, m, hl, ?_, hb⟩
    simpa [hmsg] using hs

/-- The intrinsic message is precisely the image of the kernel of the internal
map under the separator map, expressed as an existential characterization. -/
theorem mem_intrinsicMessage_iff
    (JA : LA →ₗ[𝕜] XA)
    (JAS : LA →ₗ[𝕜] XS)
    (s : XS) :
    s ∈ IntrinsicMessage JA JAS ↔
      ∃ l : LA, l ∈ LinearMap.ker JA ∧ JAS l = s := by
  rfl

end CMPLean
